<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Log Watcher</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="css/bootstrap-responsive.css" rel="stylesheet">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Log Watcher</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <?php foreach($this->getFiles() as $_code => $_file): ?>
              <li><a href="#" data-file="<?php echo $_code ?>"><i class="icon-warning-sign icon-white"></i> <?php echo $_file['label'] ?></a></li>
              <?php endforeach ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <?php foreach($this->getFiles() as $_code => $_file): ?>
      <div class="span12" data-file="<?php echo $_code ?>" data-latest="<?php echo $this->getLatestDate($_code) ?>">
        <h1><?php echo $_file['label'] ?> <small><?php echo $_file['location'] ?></small></h1>
        <pre><code><?php foreach($this->getLastLines($_code, 500) as $_l => $_line): ?><span class="lineno"><?php echo str_pad($_l+1, 4, ' ', STR_PAD_LEFT) ?></span><span class="message"><?php echo htmlentities($_line) ?></span>
<?php endforeach ?></code></pre>
      </div>
      <?php endforeach ?>
    </div> <!-- /container -->
    

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/watcher.js"></script>

  </body>
</html>